### ISSUE TITLE
Broken link to Bokeh integration annotation in 1.3.4 docs

### ISSUE THREAD

**Issue by AlexFiliakov** [bokeh/docs.bokeh.org#2]
I'm looking at Integration Tests section of this page:
https://docs.bokeh.org/en/latest/docs/dev_guide/testing.html#id1

It points readers to a link to `test_whisker.py`, but that link is broken

This is the GitHub HTML page:
https://github.com/bokeh/docs.bokeh.org/blob/master/en/1.3.4/docs/dev_guide/testing.html#L443

**Comment by AlexFiliakov** [comment]
Looks like the tests have been rearranged, the closest reference I can find is here:
https://github.com/bokeh/bokeh/blob/38c148fef2bb9e412750df89d701d047f10e5274/bokeh/models/tests/test_annotations.py

**Comment by bryevdv** [comment]
That whole chapter is out of date. I will be re-writing it shortly. Thanks for the note (FYI the main repo is the place for issues like this, this repo is just a static archive for already-built docs)
